In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
path = r"/content/Standout2019.csv"
data = pd.read_csv(path)

In [ ]:
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(data[["Profile"]])
profile_encoded = onehot_encoder.transform(data[["Profile"]])
onehot_profile = profile_encoded.toarray()
print(onehot_profile)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
data[["profileA","profileB","profileC","profileD","profileE","profileF","profileG"]] = onehot_profile
data

Thickness  Length Profile      Stress  profileA  profileB  profileC  \
0        0.115    3000       A   814.43463       1.0       0.0       0.0   
1        0.120    3250       A  1171.89320       1.0       0.0       0.0   
2        0.125    3250       A  1026.75990       1.0       0.0       0.0   
3        0.130    3000       A   677.87006       1.0       0.0       0.0   
4        0.135    3250       A   822.44940       1.0       0.0       0.0   
..         ...     ...     ...         ...       ...       ...       ...   
198      0.235    7250       G  1260.59880       0.0       0.0       0.0   
199      0.240    7000       G  1196.55750       0.0       0.0       0.0   
200      0.245    7500       G  1300.36840       0.0       0.0       0.0   
201      0.250    7250       G  1221.70650       0.0       0.0       0.0   
202      0.255    7500       G  1264.69910       0.0       0.0       0.0   

     profileD  profileE  profileF  profileG  
0         0.0       0.0       0.0       0.0  
1         0.0       0.0       0.0       0.0  
2         0.0       0.0       0.0       0.0  
3         0.0       0.0       0.0       0.0  
4         0.0       0.0       0.0       0.0  
..        ...       ...       ...       ...  
198       0.0       0.0       0.0       1.0  
199       0.0       0.0       0.0       1.0  
200       0.0       0.0       0.0       1.0  
201       0.0       0.0       0.0       1.0  
202       0.0       0.0       0.0       1.0  

[203 rows x 11 columns]

In [ ]:
data = data.drop(["Profile","Stress","profileG"], axis=1)
s_data = data.sample(frac=1)

x = s_data[["Thickness","profileA","profileB","profileC","profileD","profileE","profileF"]]
y = s_data["Length"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
print(x_train)

[[0.23  0.    0.    ... 0.    1.    0.   ]
 [0.115 0.    1.    ... 0.    0.    0.   ]
 [0.245 0.    0.    ... 0.    0.    0.   ]
 ...
 [0.115 0.    0.    ... 1.    0.    0.   ]
 [0.18  0.    0.    ... 1.    0.    0.   ]
 [0.185 0.    0.    ... 1.    0.    0.   ]]


In [ ]:
scaler = StandardScaler()
scaler.fit(x_train)
x1_train = scaler.transform(x_train)
x1_test = scaler.transform(x_test)
print(x1_train)

[[ 1.05280738 -0.42640143 -0.41736501 ... -0.39904344  2.50599282
  -0.41736501]
 [-1.67432857 -0.42640143  2.39598429 ... -0.39904344 -0.39904344
  -0.41736501]
 [ 1.40852076 -0.42640143 -0.41736501 ... -0.39904344 -0.39904344
  -0.41736501]
 ...
 [-1.67432857 -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]
 [-0.1329039  -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]
 [-0.01433277 -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]]


In [ ]:
# Calculate mean and standard deviation
mean = np.mean(x_train, axis=0)
std_dev = np.std(x_train, axis=0)

# Standardize the training and test data
X2_train = (x_train - mean) / std_dev
X2_test = (x_test - mean) / std_dev

print(X2_train)

[[ 1.05280738 -0.42640143 -0.41736501 ... -0.39904344  2.50599282
  -0.41736501]
 [-1.67432857 -0.42640143  2.39598429 ... -0.39904344 -0.39904344
  -0.41736501]
 [ 1.40852076 -0.42640143 -0.41736501 ... -0.39904344 -0.39904344
  -0.41736501]
 ...
 [-1.67432857 -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]
 [-0.1329039  -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]
 [-0.01433277 -0.42640143 -0.41736501 ...  2.50599282 -0.39904344
  -0.41736501]]
